### ISSUE TITLE
Add Scott Nichols as a zeitgeist maintainer

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/zeitgeist#16]
#### What would you like to be added:

Add @n3wscott as a zeitgeist maintainer.

#### Why is this needed:

From https://github.com/kubernetes/org/issues/2299:
> Scott recently [donated](https://github.com/kubernetes-sigs/zeitgeist/pull/14) buoy (https://github.com/n3wscott/buoy) to zeitgeist (https://github.com/kubernetes-sigs/zeitgeist) and we'll be adding his as a maintainer to help [integrate the two tools](https://github.com/kubernetes-sigs/zeitgeist/issues/15)!

#### Tracking:

- [x] k-sigs org membership request: https://github.com/kubernetes/org/issues/2299
- [x] k/org team updates: https://github.com/kubernetes/org/pull/2300
- [x] Add OWNERS for `buoy/`: https://github.com/kubernetes-sigs/zeitgeist/pull/17
- [ ] Promote to approver post-buoy integration: 

/assign

**Comment by n3wscott** [comment]
Thanks for add this!

**Comment by cpanato** [comment]
this is done
/close
