### ISSUE TITLE
JSON output for extensibility

### ISSUE THREAD

**Issue by chlunde** [kubernetes-sigs/zeitgeist#21]
#### What would you like to be added:

I would like support for JSON output for exensibility. I think the output should include at least:

##### The matches (w/ byte offsets) of each version found in different files 
This would allow another program to easily change the version tag and run CI or create a PR to bump it (kind of like dependabot). This must be the offsets where the version should be stored, in a consistent with regards to prefixes like "v" and quotes. An alternative to the byte offset would be to have a mode to run this program in to set the version of a named component in the inventory and referenced files.

##### A more complete set of possible "next version"
It's difficult to say exactly what versions should be included. There are multiple different candidates for upgrading, depending on strategies, so perhaps all versions newer than the current release would be a good idea. For downgrades, I don't think this tool would be used, but more likely a `git revert` or a hand picked version.
A more compact option would be to include:
* The next patch version (cur + 0.0.1) - if any
* The latest patch version (cur +0.0.(max)) - if any
* The next minor release (cur + 0.1.(max)) - if any
* The latest minor release (cur + 0.(max).(max)) - if any
* The latest major release (cur + (max).(max).(max)) - if any
Given that we will not have any system for dependencies across components, known buggy versions etc., these are the versions I think I would most likely consider.

##### Links to changelogs
For humans to review

##### The timestamp of each release
This could be helpful for deciding if a version is likely unmaintained (time for upgrade to next minor/major) when on the latest patch level.

#### Why is this needed:
I think this will open up for more automation, like dependabot or CI jobs which fail when using stale patch versions, and also CLI tools to manually run to upgrade components. Some of these features probably should be considered directly in this tool, depending on the scope of the project.

**Comment by saschagrunert** [comment]
Hey @chlunde, thank you for the request! :pray: 

This seems a valuable addition to me. Are you planning to provide the enhancement by yourself?

**Comment by ykakarap** [comment]
I logged a a broader issue to support different output formats at #30 
I will work on adding this feature.  

/assign

**Comment by saschagrunert** [comment]
/remove-lifecycle stale

@ykakarap do you have any update on this one?

**Comment by ykakarap** [comment]
@saschagrunert this issue is already addressed in this PR https://github.com/kubernetes-sigs/zeitgeist/pull/31

This issue can be closed.

**Comment by saschagrunert** [comment]
Yep, thank you!

/close
