### ISSUE TITLE
Consider adding fields for interpreting a base image or tooltip/description

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/zeitgeist#47]
#### What would you like to be added:

Fields for interpreting a base image or tooltip/description

#### Why is this needed:

From @tpepper in https://github.com/kubernetes/release/pull/2081#issuecomment-850510327:

> > @tpepper -- thanks for the suggestion!
> > Each of the comments are actually representative of the dependency we're tracking, as in, "these various entries are things you should look at updating when managing the `distroless` dependency".
> > In this case, we're saying that you should look at updating
> > ```yaml
> > - name: "gcr.io/projectsigstore/cosign"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when updating anything that depends on distroless images.
> > Do you think there's a better way to represent this in comments?
> 
> I'd bumped into this because I was looking at something in go-runner and saw its Dockerfile referenced distroless (as I'd expect for many/most) for "production" images, and was working backwards toward version hints beyond "latest" and was grepping around for distroless things. I figured there are lots of distroless usage points, but then I saw the dependencies.yaml only saying distroless at the cosign usage and got misled by the comment pattern.
> 
> Maybe this argues for something like a
> 
> ```yaml
> - baseimagename: ""
> ```
> 
> field? This would lead to some repetition in the file, as it puts the dependency explicitly at each dependent site in the file. Today if usage going from a dependency to its base is "visually scan upward to he prior `#comment` to see the base image name for this dependency" feels somewhat obscure. If the usage is "upon seeing a `#comment` know that everything following (but before a next comment) shares usage of the base image in this comment" the current way can make sense. The other benefit though of the explicit entry in yaml instead of comments and visual scans is explicit machine readability.

**Comment by tpepper** [comment]
I'm imagining a deterministic pipeline where situations like https://kubernetes.slack.com/archives/C2C40FMNF/p1630102388026100 don't happen.  Ie: instead of discovering things missed, we know what we have and when they need bumped forward.  I think this requires annotations at a build input/output location.
