### ISSUE TITLE
New feature: warning for archived repos

### ISSUE THREAD

**Issue by Pluies** [kubernetes-sigs/zeitgeist#48]
#### What would you like to be added:

Add a warning when Zeitgeist encounters github repos that have been marked as archived.

#### Why is this needed:

Github has a feature where repositories can be marked as archived when no further development is planned. Archived repositories become read-only.

This is usually a strong signal that the project is being phased out, and depending on it may not be such a good idea anymore as it will not get any more support.

Having a warning in that case would be great for dependency tracking!

**Comment by va3093** [comment]
@Pluies that was a quick turn around
