### ISSUE TITLE
Regex to extract version ?

### ISSUE THREAD

**Issue by gaetansnl** [kubernetes-sigs/zeitgeist#563]
To my understanding zeitgeist is only supporting correct semver tags. But some containers are tagged like `amd64-1.2.1`, etc...
It could be nice if we can filter tags based on regex and extract the semver version

**Comment by Pluies** [comment]
Hi @gaetansnl ! That sounds like a good feature, would you like to give it a go?

**Comment by gaetansnl** [comment]
I can, I'll take a look at the code.

**Comment by saschagrunert** [comment]
Would something like this not be sufficient:

https://github.com/kubernetes-sigs/security-profiles-operator/blob/73a4eeddc8e4fe6543bf6e5309cf86490c983b3a/dependencies.yaml#L112-L116

**Comment by gaetansnl** [comment]
@saschagrunert not sure what you mean. How zeigeist would tell the difference between arm64-1.2.1 and amd64-1.2.1 when fetching the latest available version.
