### ISSUE TITLE
zeitgeist v0.4.1 version prints to stderr not stdout breaking release-utils/mage

### ISSUE THREAD

**Issue by pnasrat** [kubernetes-sigs/zeitgeist#739]
See also kubernetes-sigs/release-utils#96 and my reproducer and notes here https://github.com/pnasrat/magedep 

This probably would need a new version of zeitgeist cut past the commit identified below

#### What happened:

```
Error: ensuring zeitgeist is installed: ensuring package: the output of /home/pnasrat/workspace/bin/zeitgeist version did not include a 3-part semver value: 
exit status 1
```

#### What you expected to happen:

No error.

#### How to reproduce it (as minimally and precisely as possible):

1. `rm -f "${GOPATH}"/bin/zeitgeist`
2. `go install sigs.k8s.io/zeitgeist@v0.4.1`
3. `zeitgeist version 2>/dev/null`

Expect to have the version printed however it is not as it is writing to stderr

## Analysis

zeitgeist@0.4.1 version writes it's version info to stderr which is not what [uwu-tools/magex]( github.com/uwu-tools/magex) expects in `GetCommandVersion` see https://github.com/uwu-tools/magex/blob/v0.10.0/pkg/install.go#L288

This can be demonstrated with `$GOPATH/bin/zeitgeist version 2>/dev/null`

This is fixed in zeitgeist from [PR 544](https://github.com/kubernetes-sigs/zeitgeist/pull/544/commits) onwards commit: https://github.com/kubernetes-sigs/zeitgeist/commit/5108cb4e034ebefd17b9e827243174344c010379

I used git bisect to identify where the change is and that can be verified 

```
git checkout 5108cb4
go run main.go version 2>/dev/null
 __  /   ____|  _ _|  __ __|    ___|   ____|  _ _|    ___|   __ __|
    /    __|      |      |     |       __|      |   \___ \      |
   /     |        |      |     |   |   |        |         |     |
 ____|  _____|  ___|    _|    \____|  _____|  ___|  _____/     _|
zeitgeist: Zeitgeist is a language-agnostic dependency checker

GitVersion:    devel
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.21.3
Compiler:      gc
Platform:      linux/amd64
```

Versus the revision  before https://github.com/kubernetes-sigs/zeitgeist/commit/a98a760d114d56f73f974794627fdd24132ce2df which outputs to stderr

```
git checkout a98a760
go run main.go  version 2>/dev/null
```

**Comment by Pluies** [comment]
[Still no luck](https://github.com/kubernetes-sigs/zeitgeist/actions/runs/6828186771/job/18618088686#step:9:356):
```
  ⨯ release failed after 15m0s               error=scm releases: failed to publish artifacts: failed to upload zeitgeist-arm-linux after 2 tries: POST https://uploads.github.com/repos/kubernetes-sigs/zeitgeist/releases/128955273/assets?name=zeitgeist-arm-linux: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

Indeed the artefact already exists, it appears that buoy and zeitgeist somehow create two artefacts with the same name (!?):
```
      • uploading to release                         file=dist/zeitgeist-amd64-darwin name=zeitgeist-amd64-darwin
      • uploading to release                         file=dist/buoy-amd64-darwin name=zeitgeist-amd64-darwin
```

@cpanato @saschagrunert , do you have any clue what could be going on?

**Comment by cpanato** [comment]
I will take care that.

I was planning to do but with kubecon was hard to do.

Will work on this today/tomorrow

**Comment by cpanato** [comment]
release is out, will update the downstreams

https://github.com/kubernetes-sigs/zeitgeist/releases/tag/v0.4.3

/close
