### ISSUE TITLE
Incorrect latest version selected for GitHub upstream

### ISSUE THREAD

**Issue by michaelsauter** [kubernetes-sigs/zeitgeist#758]
#### What happened:

When using the GitHub upstream, zeitgeist fails to select the highest version when the most recently created release is not equal to the latest release. For example, https://github.com/containers/buildah/releases currently lists v1.31.4 and v1.29.2 before the latest release, v1.32.2. zeitgeist returns v1.31.4 as the latest version.

#### What you expected to happen:

The highest version should be selected, not the one released most recently.

#### How to reproduce it (as minimally and precisely as possible):

I created a test case demonstrating the incorrect behaviour: https://github.com/michaelsauter/zeitgeist/commit/f10f89c33734e9efec09f889a889249576bf85e7.

#### Anything else we need to know?:

Interestingly, the potential issue is described in a code comment, see https://github.com/kubernetes-sigs/zeitgeist/blob/master/upstream/github.go#L103-L108. However, the code below does not seem to address the issue. Further, I found https://github.com/kubernetes-sigs/zeitgeist/issues/2, which seems related. It introduces code to fetch all release pages instead of just the first one. Surprisingly, this is missing from https://github.com/kubernetes-sigs/zeitgeist/blob/master/upstream/github.go right now.

#### Environment:

```
GitVersion:    v0.4.3
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.21.0
Compiler:      gc
Platform:      darwin/arm64
```

**Comment by saschagrunert** [comment]
cc @kubernetes-sigs/release-engineering @Pluies

**Comment by Pluies** [comment]
Thanks for the report @michaelsauter , this is pretty bad. Loking back, it does appear that #2 added the code and now fetches _all_ possible releases... But still iterates from the top, and therefore still has this bug.

I think I was probably hitting a case where a lot of newer releases were pushing the latest matching release to the second page, which meant adding pagination fixed this very specific case but didn't actually fix the larger issue.

Or maybe it was introduced when we [switched to the release-sdk github client](https://github.com/kubernetes-sigs/zeitgeist/commit/4bbb21724d2683e7e23e56f428a7162ed3fddd94)? Anyway, let's fix this.

Thank you for adding the test case too, makes it easy to replicate. On it!

**Comment by michaelsauter** [comment]
Cool. Let me know if there's anything I can help with. If you're busy, I can also work on opening a PR to fix the issue.

BTW, may be worth checking if the same behaviour may happen in other upstreams too?

**Comment by Pluies** [comment]
See PR above for the fix @michaelsauter - I've cherry-picked your tests, which means the PR now expects you to sign the CLA 😓 sorry about that, let me know if you'd rather not and I'll reimplement tests in a different commit instead.

The Gitlab upstream was affected as well. Helm returns releases pre-ordered so it's not affected, and so does the containers backend which also pre-sorts its list of releases. AMI and EKS are also unaffected as they don't really have releases in the same way.

**Comment by michaelsauter** [comment]
@Pluies Unfortunately, I believe it will take a bit of time until I would have the CLA signed as it would be a corporate contribution. Make your life easier by just re-implementing ;)

By the way, I think the solution could potentially be simplified by making use of https://pkg.go.dev/github.com/blang/semver/v4#Sort ?
